name: Data Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extractor and gold validation
        env:
          FAIL_ON_GOLD_MISSING: '1'
          ALLOW_SYNTHETIC: '1'
          FORCE_SYNTHETIC: '1'
        run: |
          python backend/app/utils/extract_gsl_dictionary.py
